services:
  postgres:
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - transcendance

  # frontend:
  #   build: ./frontend
  #   restart: always
  #   env_file: .env
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - transcendance

  backend:
    build: ./backend
    restart: always
    env_file: .env
    ports:
      - 8000:8000
    networks:
      - transcendance

  gameserver:
    build: ./gameserver-v2
    restart: always
    env_file: .env
    ports:
      - 8080:8080
    networks:
      - transcendance   

  # prometheus:
  #   image: prom/prometheus
  #   restart: always
  #   volumes:
  #     - ./prometheus:/etc/prometheus
  #   ports:
  #     - 9090:9090
  #   networks:
  #     - transcendance

  # grafana:
  #   image: grafana/grafana
  #   restart: always
  #   env_file: .env
  #   volumes:
  #     - ./grafana:/var/lib/grafana
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - transcendance

  # harvester:
  #   build: ./harvester
  #   restart: always
  #   env_file: .env
  #   networks:
  #     - transcendance

networks:
  transcendance:
    driver: bridge