services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/certs:ro
    networks:
      - transcendence

  postgres:
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - transcendence

  frontend:
    build: ./frontend
    restart: always
    env_file: .env
    networks:
      - transcendence
    volumes:
      - ./certs:/certs

  backend:
    build: ./backend
    restart: always
    env_file: .env
    networks:
      - transcendence
    volumes:
      - ./data/exports:/exports
      - ./certs:/certs

  harvester:
    build: ./harvester
    restart: always
    env_file: .env
    volumes:
      - ./data/exports:/exports
      - ./certs:/certs
    networks:
      - transcendence

  statcruncher:
    build: ./statcruncher
    restart: always
    env_file: .env
    networks:
      - transcendence
    volumes:
      - ./certs:/certs

networks:
  transcendence:
    driver: bridge
