services:
  postgres:
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transcendence

  frontend:
    build: ./frontend
    restart: always
    env_file: .env
    ports:
      - "8888:443"
    networks:
      - transcendence
    volumes:
      - certs_data:/certs

  backend:
    build: ./backend
    restart: always
    env_file: .env
    networks:
      - transcendence
    volumes:
      - exports_data:/exports
      - certs_data:/certs

  harvester:
    build: ./harvester
    restart: always
    env_file: .env
    volumes:
      - exports_data:/exports
    networks:
      - transcendence

  statcruncher:
    build: ./statcruncher
    restart: always
    env_file: .env
    networks:
      - transcendence
    volumes:
      - certs_data:/certs

networks:
  transcendence:
    driver: bridge

volumes:
  postgres_data:
  exports_data:
  certs_data:
