services:
  postgres:
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - transcendance

  # rabbitmq:
  #   image: rabbitmq
  #   restart: always
  #   env_file: .env
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   networks:
  #     - backend

  backend:
    build: ./backend
    restart: always
    env_file: .env
    ports:
      - 8000:8000
    networks:
      - transcendance

  harvester:
    build: ./harvester
    restart: always
    env_file: .env
    networks:
      - transcendance

networks:
  transcendance:
    driver: bridge
