app = 'transcendence-api'
project = 'transcendence'
region = 'eu-west-1'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  dns_name = trans.evan.sh 
  path = '/api'

[vm]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  replicas = 1