global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __address__
        replacement: postgres:5432

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __address__
        replacement: backend:8000

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __address__
        replacement: grafana:3000