apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: registry.propel.sh/transcendence/backend:latest
          envFrom:
            - configMapRef:
                name: app-config
          volumeMounts:
            - name: exports-storage
              mountPath: /exports
      volumes:
        - name: exports-storage
          persistentVolumeClaim:
            claimName: exports-data
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend
  ports:
    - port: 8443