apiVersion: apps/v1
kind: Deployment
metadata:
  name: harvester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harvester
  template:
    metadata:
      labels:
        app: harvester
    spec:
      runtimeClassName: kata
      containers:
        - name: harvester
          image: registry.propel.sh/transcendence/harvester:latest
          envFrom:
            - configMapRef:
                name: app-config
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          volumeMounts:
            - name: exports-storage
              mountPath: /exports
      volumes:
        - name: exports-storage
          persistentVolumeClaim:
            claimName: exports-data