http:
  routers:
    frontend:
      rule: "PathPrefix(`/`)"
      service: frontend
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: myresolver
    backend:
      rule: "PathPrefix(`/api`)"
      service: backend
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: myresolver
    backend-websocket:
      rule: "PathPrefix(`/ws`)"
      service: backend-websocket
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: myresolver

  services:
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:3000"
    backend:
      loadBalancer:
        servers:
          - url: "http://backend:8000"
    backend-websocket:
      loadBalancer:
        servers:
          - url: "http://backend:8000"
    gameserver:
      loadBalancer:
        servers:
          - url: "http://gameserver:8080"