http:
  routers:
    frontend:
      rule: "PathPrefix(`/`)"
      service: frontend
      entryPoints:
        - websecure
      tls:
        insecureSkipVerify: true
    backend:
      rule: "PathPrefix(`/api`)"
      service: backend
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: myresolver
    backend-websocket:
      rule: "PathPrefix(`/ws`)"
      service: backend-websocket
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: myresolver

  services:
    frontend:
      loadBalancer:
        servers:
          - url: "https://frontend:3000"
    backend:
      loadBalancer:
        servers:
          - url: "https://backend:8443"

  serversTransports:
    insecureSkipVerify: true