name: "Build and Push Docker Images"

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend, gameserver-v2, harvester]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v2
      with:
        registry: rg.fr-par.scw.cloud
        username: ${{ secrets.SCW_ACCESS_KEY }}
        password: ${{ secrets.SCW_SECRET_KEY }}

    - name: Build and push ${{ matrix.service }} image
      uses: docker/build-push-action@v4
      with:
        context: ./${{ matrix.service }}
        push: true
        tags: rg.fr-par.scw.cloud/evansh/${{ matrix.service }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max