name: "Build and Push Docker Images"

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend, harvester, statcruncher, pongbot, certs]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Propel Container Registry
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        registry: registry.propel.sh
        username: ${{ secrets.PROPEL_REGISTRY_USER }}
        password: ${{ secrets.PROPEL_REGISTRY_TOKEN }}

    - name: Build and push ${{ matrix.service }} image
      uses: docker/build-push-action@v4
      with:
        context: ./${{ matrix.service }}
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: registry.propel.sh/transcendence/${{ matrix.service }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max